-- Script generated by pgAdminIII

-- Table: public.plots

-- DROP TABLE public.plots;

CREATE TABLE public.plots
(
  id character varying(32) NOT NULL,
  pew character varying(16),
  pew2 character varying(16),
  pew3 character varying(8),
  CONSTRAINT id PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE public.plots
  OWNER TO darek;
